GET localhost:8080/day06-response-request/resp/demo01

###


GET localhost:8080/day06-response-request/resp/demo02


###


GET localhost:8080/day06-response-request/resp/demo03

###


GET localhost:8080/day06-response-request/resp/demo04

###


GET localhost:8080/day06-response-request/resp/demo05

###


GET localhost:8080/day06-response-request/resp/demo06